### ISSUE TITLE
Invalid Query is generated: Each GROUP BY expression must contain at least one column that is not an outer reference.

### ISSUE THREAD

**Issue by theosotr** [ESSolutions/django-mssql-backend#62]
I have the following simple query which runs on SQL Server.

```python
expr = ExpressionWrapper(
     (Value(10) - Value(5)) - Sum(F('colA')), output_field=FloatField())
Table.objects.values('colb').annotate(expr=expr)
```

this backend generates the following SQL query

```sql
SELECT ((%s - %s) - SUM([table].[colA])) AS [expr] FROM [table] GROUP BY [table].[colB], (%s - %s)

```

the issue here is that the query above seems to be illegal as the code crashes with the exception below

```
Traceback (most recent call last):
  File "/home/.env/lib/python3.6/site-packages/Django-3.2-py3.6.egg/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/.env/lib/python3.6/site-packages/sql_server/pyodbc/base.py", line 553, in execute
    return self.cursor.execute(sql, params)
pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Each GROUP BY expression must contain at least one column that is not an outer reference. (164) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "driver_mssql.py", line 28, in <module>
    for r in ret2:
  File "/home/.env/lib/python3.6/site-packages/Django-3.2-py3.6.egg/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/home/.env/lib/python3.6/site-packages/Django-3.2-py3.6.egg/django/db/models/query.py", line 1316, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/.env/lib/python3.6/site-packages/Django-3.2-py3.6.egg/django/db/models/query.py", line 111, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/home/.env/lib/python3.6/site-packages/Django-3.2-py3.6.egg/django/db/models/sql/compiler.py", line 1115, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/home/.env/lib/python3.6/site-packages/Django-3.2-py3.6.egg/django/db/models/sql/compiler.py", line 1160, in execute_sql
    cursor.execute(sql, params)
  File "/home/.env/lib/python3.6/site-packages/Django-3.2-py3.6.egg/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/.env/lib/python3.6/site-packages/Django-3.2-py3.6.egg/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/.env/lib/python3.6/site-packages/Django-3.2-py3.6.egg/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/.env/lib/python3.6/site-packages/Django-3.2-py3.6.egg/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/.env/lib/python3.6/site-packages/Django-3.2-py3.6.egg/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/.env/lib/python3.6/site-packages/Django-3.2-py3.6.egg/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/.env/lib/python3.6/site-packages/sql_server/pyodbc/base.py", line 553, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Each GROUP BY expression must contain at least one column that is not an outer reference. (164) (SQLExecDirectW)')
```

**Comment by morlandi** [comment]
Any idea on this ?
